Autonomous missions
TeamCautionRobotics/2018-FRC-robot pull request #35
Opened 2018-02-25 23:48 UTC by TaeSeanDo

Closes #16, #21, #29, #31.

2018-02-27 03:56 UTC, docprofsky requested changes

2018-02-27 03:56 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/AutoEnums.java
> +        SWITCH("switch"), SCALE("scale"), SWITCH_OR_SCALE("auto select switch and scale"), AUTO_LINE("auto line"), DO_NOTHING("do nothing");
A better description for `SWITCH_OR_SCALE` might be "Automatically select switch, scale, or line".

2018-02-27 03:56 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Robot.java
> +        autoObjectiveChooser.addObject("Do nothing", AutoObjective.DO_NOTHING);
Can you use the `.toString()` methods of these enums? Also, a for loop like this could be used to populate these choosers.
```Java
StartingPosition defaultPosition = StartingPosition.CENTER;
startingPositionChooser.addDefault(defaultPosition.toString(), defaultPosition);
for (StartingPosition position : StartingPosition.values()) {
    if (position == defaultPosition) {
        continue;
    }
    startingPositionChooser.addObject(position.toString(), position);
}
```

2018-02-27 03:56 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Robot.java
> +        System.out.println("dsg " + fmsData);
Log message?

2018-02-27 03:56 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Robot.java
>          SmartDashboard.putData("Autonomous Mode Select", missionChooser);
The "Autonomous Mode Select"ion is not used. I believe this was going to be used to select whether the mission selection logic runs.

2018-02-27 03:56 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/MissionSelector.java
> +                        switchSide.toString(), scaleSide.toString(), startingPosition.toString(),
We should probably throw an exception here instead of the error mission, but this does not need to be changed to be merged.

2018-03-05 23:55 UTC, TaeSeanDo commented on src/com/teamcautionrobotics/robot2018/Robot.java
> +        System.out.println("dsg " + fmsData);
covfefe.

2018-03-06 05:06 UTC, docprofsky approved these changes

2018-03-06 05:40 UTC, merged