Robot controls for drive team
TeamCautionRobotics/2018-FRC-robot pull request #37
Opened 2018-02-26 01:28 UTC by docprofsky

Closes #32.

2018-02-28 22:24 UTC, TaeSeanDo requested changes

2018-02-28 22:24 UTC, TaeSeanDo commented on src/com/teamcautionrobotics/misc2018/FunctionRunnerSendable.java
> +public class FunctionRunnerSendable extends SendableBase implements Sendable {
Should include a javadoc to explain the purpose of this class.

2018-02-28 22:24 UTC, TaeSeanDo commented on src/com/teamcautionrobotics/robot2018/Robot.java
> +            lift.setHeight(lift.getCurrentHeight());
setHeight should probably be renamed to setHeightPID.

2018-02-28 22:24 UTC, TaeSeanDo commented on src/com/teamcautionrobotics/robot2018/Robot.java
> +        liftResetSendable = new FunctionRunnerSendable("Reset lift", () -> {
This should probably be renamed to liftResetEncoderSendable; put "reset lift encoder" as the string as well.

2018-02-28 22:24 UTC, TaeSeanDo commented on src/com/teamcautionrobotics/robot2018/Robot.java
>              if (manipulator.getButton(Button.LEFT_BUMPER)) {
Spinning should also be disabled if driverPrismHarvesting.

2018-02-28 22:24 UTC, TaeSeanDo commented on src/com/teamcautionrobotics/robot2018/Robot.java
> +        intake.move(grabberPower, intakePower);
This may conflict with a timed spin or a bulldoze by resetting motor values.

2018-03-01 00:51 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Robot.java
> +            lift.setHeight(lift.getCurrentHeight());
How about `setDestinationHeight`?

2018-03-03 01:59 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Robot.java
> +        intake.move(grabberPower, intakePower);
That is not how [`intake.move()`](https://github.com/TeamCautionRobotics/2018-FRC-robot/blob/456c31387e297dd80e6aa24ff4c6b0b2adb8138d/src/com/teamcautionrobotics/robot2018/Intake.java#L39-L47) works.

2018-03-05 23:08 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Robot.java
> +        intake.move(grabberPower, intakePower);
Though, the bulldoze part might be a problem.

2018-03-05 23:36 UTC, TaeSeanDo approved these changes

2018-03-05 23:41 UTC, merged