Intake rotator
TeamCautionRobotics/2018-FRC-robot pull request #48
Opened 2018-03-31 02:27 UTC by TaeSeanDo

Not for merging. Uses "angular optimizer" with PID.

2018-04-05 20:29 UTC, docprofsky approved these changes
I approve my own changes.

2018-04-05 20:37 UTC, TaeSeanDo commented
I do not know when I am using someone else's account, so I hijacked @docprofsky's and used his account to approve my changes.

2018-04-05 21:48 UTC, docprofsky requested changes
Angulator is probably a better name than Angular Optimizer.
We might want functions to enable and disable the Angulator PID controller.
Also, you need to make your pull requests more atomic. You _really_ should not be addressing a _low priority_ issue that was created after a pull request was opened in said issue.

2018-04-05 21:48 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Harvester.java
> +        private static HarvesterAngle[] values = values();
Someone did a copy pasta.

2018-04-05 21:48 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Harvester.java
> +        UP(90), AIMED(45), DOWN(0);
`AIMED` might not be the best name.

2018-04-05 21:48 UTC, docprofsky commented on src/com/teamcautionrobotics/autonomous2018/commands/CommandFactory2018.java
> +    public Command rotateHarvester(double angle) {
We might want `waitForRotation` to default to false.

2018-04-05 21:48 UTC, docprofsky commented on src/com/teamcautionrobotics/autonomous2018/commands/MoveIntakeCommand.java
> +     * Run the harvester for a period of time. Waits for the lift to be at its destination before
You missed a spot.

2018-04-05 21:48 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Harvester.java
> +        angularOptimizerEncoder.setDistancePerPulse(360 / 1024);
This scaling factor will be wrong, since there are gears with non-unity ratios between the encoder and the grabber.

2018-04-05 21:48 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Harvester.java
> +            double midpoint = harvesterAngle.angle + 22.5;
Do we really _need_ a magic number?

2018-04-05 21:48 UTC, docprofsky commented on src/com/teamcautionrobotics/robot2018/Robot.java
> +        if (driverLeft.getRawButton(0)) {
You might want `driverLeft.getTrigger()`.

2018-04-06 04:30 UTC, docprofsky commented on src/com/teamcautionrobotics/autonomous2018/commands/CommandFactory2018.java
> +    public Command rotateHarvester(double angle) {
@TaeSeanDo said that true is a good default for `waitForRotation`. I trust him.

2018-04-06 04:30 UTC, docprofsky approved these changes

2018-04-07 23:38 UTC, docprofsky commented
@TaeSeanDo is going to look this over and merge it.

2018-04-28 02:59 UTC, merged